# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('game_date', models.DateField(max_length=8, null=True)),
                ('game_review', models.TextField(max_length=1000, null=True)),
                ('logo_url', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pundit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pundit_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team_logo_url', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pundit',
            name='favorite_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadia.Team'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadia.Pundit'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadia.Team'),
        ),
    ]
